import './globals.css'

import classNames from 'classnames'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type RootLayoutProps = {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  const bodyStyles = classNames(
    inter.className,
    `text-black dark:text-gray-50`,
    `bg-white dark:bg-gray-950`,
    `transition-colors duration-300`
  )

  return (
    <html lang="ko" className="">
      <body className={bodyStyles}>{children}</body>
    </html>
  )
}
